set preview_images true
set preview_images_method ueberzug
set confirm_on_delete multiple
set show_hidden true
set scroll_offset 8
set update_title true
set save_console_history false

# mappings
map dD shell trash-put %s
map uD shell trash-restore

